### ISSUE TITLE
Incomplete gcloud print-access-token error

### ISSUE THREAD

**Issue by jankrynauw** [google/googlesource-auth-tools#2]
Trying to run the following in a docker container:

```
FROM gcr.io/google.com/cloudsdktool/cloud-sdk
ENTRYPOINT ["bash"]
WORKDIR /app
RUN git clone https://github.com/google/googlesource-auth-tools.git githelper
RUN chmod +x githelper/googlesource-cookieauth/googlesource-cookieauth
RUN githelper/googlesource-cookieauth/googlesource-cookieauth
```
and gets the following error:
```
Cannot write cookies: cannot create a token for https://googlesource.com: credentials: cannot get a token: credentials: incomplete gcloud print-access-token result: &{ {}}
```
Any guidance as to what I'm doing wrong?

The context is:

- We have a private repo in golang, hosted on Google Source Repository (GSR)
- The `go mod download` uses git in the background
- and therefore requires the credential helper to connect to GSR
- I was hoping one could solve this with the above `google-auth-tools` library
- The above runs as part of a Google Cloud Build step (which has --network=cloudbuild set and therefore access to default credentials.)

**Comment by draftcode** [comment]
If the account config is not set, it falls back to gcloud.

https://github.com/google/googlesource-auth-tools/blob/0f4fd0ccc864c27259e7edb9b0986293320af94a/credentials/credentials.go#L65

 Because of this, it tried to run gcloud and I think it's missing there. See the configurations section (https://github.com/google/googlesource-auth-tools#configurations) as well. `google.account` defaults to `gcloud`.

If you have a default credential there, you can run `git config google.account application-default` before running googlesource-cookieauth.
